export const ADD_CHAT = 'CHATS::ADD_CHAT';
export const MARK_CHAT_ATTENTION = 'CHATS::MARK_CHAT_ATTENTION';
export const REMOVE_CHAT = 'CHATS::REMOVE_CHAT';

export const SEND_MESSAGE = 'MESSAGES::SEND_MESSAGE';
export const REMOVE_MESSAGE = 'MESSAGES::REMOVE_MESSAGE';
export const REMOVE_MESSAGE_FROM_CHAT = 'MESSAGES::REMOVE_MESSAGE_FROM_CHAT';

export default {
    ADD_CHAT,
    MARK_CHAT_ATTENTION,
    REMOVE_CHAT,

    SEND_MESSAGE,
    REMOVE_MESSAGE,
    REMOVE_MESSAGE_FROM_CHAT
}